levelhq/level

- .circleci/config.yml
- assets/elm/src/Query/AppState.elm
- assets/elm/src/Signup.elm
- assets/elm/tests/SignupTest.elm
- assets/js/modules/signup.js
- lib/level/spaces.ex
- lib/level/spaces/registration.ex
- lib/level/spaces/user.ex
- lib/level_web/controllers/session_controller.ex
- lib/level_web/plugs/auth.ex
- lib/level_web/schema/enums.ex
- lib/level_web/schema/types.ex
- lib/level_web/templates/invitation/show.html.eex
- lib/level_web/templates/session/new.html.eex
- lib/level_web/views/api/user_view.ex
- priv/repo/migrations/20180402172104_drop_username_from_users.exs
- priv/repo/structure.sql
- test/level/spaces/registration_test.exs
- test/level/spaces/user_test.exs
- test/level/spaces_test.exs
- test/level_web/controllers/accept_invitation_controller_test.exs
- test/level_web/controllers/session_controller_test.exs
- test/level_web/graphql/queries/viewer_test.exs
- test/level_web/plugs/auth_test.exs
- test/level_web/views/api/space_view_test.exs
- test/level_web/views/api/user_view_test.exs
- test/support/test_helpers.ex
> Remove username from users

- lib/level/connections.ex
- lib/level/connections/groups.ex
- lib/level/groups.ex
- lib/level_web/schema/connections.ex
- lib/level_web/schema/enums.ex
- lib/level_web/schema/input_objects.ex
- lib/level_web/schema/types.ex
- test/level/connections_test.exs
- test/level/groups_test.exs
- test/level_web/graphql/queries/groups_test.exs
> List groups belonging to a space

- lib/level/connections/groups.ex
- lib/level/groups.ex
- lib/level/groups/group_membership.ex
- lib/level_web/resolvers/group_resolver.ex
- priv/repo/migrations/20180404204544_create_group_memberships.exs
- priv/repo/structure.sql
- test/level/groups_test.exs
- test/level_web/graphql/queries/groups_test.exs
> Establish group membership upon group creation

- .circleci/config.yml
- mix.exs
> Upgrade elixir

- lib/level/connections.ex
- lib/level/connections/groups.ex
- lib/level/connections/invitations.ex
- lib/level/connections/users.ex
- lib/level/pagination/validations.ex
- script/bootstrap
- script/build
- script/docs
- script/elixir-test
- script/elm-test
- script/lint
- script/prettier
- script/server
- script/static-analysis
- script/stylelint
- script/test
- test/level/connections_test.exs
- test/level/pagination/validations_test.exs
- test/level_web/graphql/queries/space_test.exs
In addition, clean up some scripts.
> Add basic validations to pagination args on connections

- .circleci/config.yml
- lib/level/groups.ex
- lib/level/groups/group.ex
- lib/level/groups/group_membership.ex
- lib/level/spaces/user.ex
- lib/level_web/resolvers/group_resolver.ex
- lib/level_web/schema.ex
- lib/level_web/schema/mutations.ex
- script/static-analysis
- test/level/groups_test.exs
- test/level_web/graphql/mutations/update_group_test.exs
Fixes #24
Developed in tandem with @r00k (screencast forthcoming)
- User can update group if the group is public or they are member and it is in their space
> Implement updateGroup mutation

- lib/level/spaces.ex
- lib/level/spaces/invitation.ex
- lib/level/spaces/space.ex
- mix.exs
> Add typespecs to Spaces context

- lib/level/connections.ex
- lib/level/connections/group_memberships.ex
- lib/level/groups/group_membership.ex
- lib/level/pagination.ex
- lib/level/pagination/result.ex
- lib/level/spaces.ex
- lib/level_web/schema.ex
- lib/level_web/schema/connections.ex
- lib/level_web/schema/types.ex
- test/level/connections_test.exs
- test/level_web/graphql/queries/group_memberships_test.exs
> Add group memberships connection to users

- lib/level/connections.ex
- lib/level/connections/group_memberships.ex
- lib/level/connections/groups.ex
- lib/level/connections/invitations.ex
- lib/level/connections/users.ex
- lib/level/groups.ex
- lib/level/pagination.ex
- lib/level/pagination/args.ex
- lib/level/pagination/validations.ex
- mix.exs
- test/level/connections_test.exs
- test/level/groups_test.exs
- test/level/pagination/validations_test.exs
- test/level/pagination_test.exs
- test/level_web/graphql/queries/groups_test.exs
> Restrict groups exposed via connections to those visible to current user

- README.md
- app.json
- elixir_buildpack.config
- mix.exs
- script/get-erlang-version
> Fix Heroku dependencies

- lib/level/mutations.ex
- lib/level/posts.ex
- lib/level/posts/post.ex
- lib/level_web/schema.ex
- lib/level_web/schema/enums.ex
- lib/level_web/schema/mutations.ex
- lib/level_web/schema/types.ex
- priv/repo/migrations/20180413214033_create_posts.exs
- priv/repo/structure.sql
- test/level/posts_test.exs
- test/level_web/graphql/mutations/create_post_test.exs
- test/support/test_helpers.ex
> Ability to create a post

- assets/css/app.css
- assets/elm/src/Space.elm
- assets/tailwind.js
- lib/level/spaces.ex
- lib/level/spaces/open_invitation.ex
- lib/level_web/controllers/open_invitation_controller.ex
- lib/level_web/router.ex
- lib/level_web/templates/open_invitation/show.html.eex
- test/level/spaces_test.exs
- test/level_web/controllers/open_invitation_controller_test.exs
- test/level_web/graphql/queries/open_invitation_test.exs
> Wire up open invitation flow

- assets/elm/src/Event.elm
- assets/elm/src/Ports.elm
- assets/elm/src/Query/InitSpace.elm
- assets/elm/src/Socket.elm
- assets/elm/src/Space.elm
- assets/elm/src/Subscription/GroupBookmarked.elm
- assets/elm/src/Subscription/GroupUnbookmarked.elm
- assets/elm/src/Util.elm
- assets/js/ports.js
- lib/level/groups.ex
- lib/level/mutations.ex
- lib/level/spaces.ex
- lib/level_web/schema.ex
- lib/level_web/schema/mutations.ex
- lib/level_web/schema/subscriptions.ex
- lib/level_web/schema/types.ex
- test/level_web/graphql/mutations/bookmark_group_test.exs
- test/level_web/graphql/subscriptions/group_bookmarked_test.exs
- test/level_web/graphql/subscriptions/group_unbookmarked_test.exs
- test/support/channel_case.ex
> Add pubsub events for group bookmarks

- assets/elm/src/GraphQL.elm
- assets/elm/src/Mutation/BulkCreateGroups.elm
- assets/elm/src/Mutation/CompleteSetupStep.elm
- assets/elm/src/Mutation/CreateSpace.elm
- assets/elm/src/Page/Group.elm
- assets/elm/src/Query/SharedState.elm
- assets/elm/src/Route.elm
- assets/elm/src/Space.elm
- lib/level/connections.ex
- lib/level/connections/group_memberships.ex
- lib/level/connections/groups.ex
- lib/level/connections/space_memberships.ex
- lib/level_web/schema.ex
- lib/level_web/schema/types.ex
- test/level_web/graphql/queries/group_test.exs
> View a group

- assets/css/app.css
- assets/elm/src/Avatar.elm
- assets/elm/src/Data/GroupUser.elm
- assets/elm/src/Page/Group.elm
- assets/tailwind.js
- lib/level/connections.ex
- lib/level/connections/group_memberships.ex
- lib/level/connections/user_group_memberships.ex
- lib/level/groups/group_user.ex
- lib/level_web/schema/types.ex
- test/level_web/graphql/queries/user_group_memberships_test.exs
> Display group members

- assets/elm/src/Page/Group.elm
- assets/elm/src/Space.elm
- assets/elm/src/Util.elm
> Display the current day on posts

- assets/elm/src/Page/Group.elm
- lib/level/connections.ex
- lib/level/groups.ex
- lib/level_web/schema/types.ex
- test/level_web/graphql/queries/featured_memberships_test.exs
- test/support/test_helpers.ex
> Featured memberships

- lib/level/markdown.ex
- test/level/markdown_test.exs
Fixes #90
See https://github.com/pragdave/earmark#details
> Make all line breaks significant

- assets/css/app.css
- lib/level/posts.ex
- lib/level/posts/create_reply.ex
- lib/level/users.ex
- lib/level/web_push.ex
- test/level/users_test.exs
- test/level/web_push_test.exs
- test/level_web/graphql/mutations/register_push_subscription_test.exs
> Only send push notifications to subscribers who are present

- assets/css/app.css
- assets/elm/src/Component/Post.elm
- assets/elm/src/Connection.elm
- assets/elm/src/Page/Inbox.elm
- assets/elm/src/Program/Main.elm
- assets/elm/src/Query/InboxInit.elm
- assets/elm/src/ReplyComposer.elm
- assets/elm/src/Route/Inbox.elm
- assets/elm/src/Space.elm
- assets/elm/src/View/Layout.elm
- assets/tailwind.js
- lib/level/resolvers/post_connection.ex
- lib/level_web/schema/enums.ex
- lib/level_web/schema/input_objects.ex
- test/level_web/graphql/queries/posts_test.exs
> Inbox filters

- assets/elm/src/Component/Post.elm
- assets/elm/src/Mutation/UpdatePost.elm
- assets/elm/src/Post.elm
- assets/elm/src/PostEditor.elm
- assets/elm/src/Subscription/PostSubscription.elm
- assets/elm/src/ValidationError.elm
- lib/level/events.ex
- lib/level/mutations.ex
- lib/level/post_version.ex
- lib/level/posts.ex
- lib/level/posts/create_post.ex
- lib/level/posts/create_reply.ex
- lib/level/posts/post.ex
- lib/level/posts/post_log.ex
- lib/level/posts/update_post.ex
- lib/level/resolvers.ex
- lib/level_web/schema.ex
- lib/level_web/schema/mutations.ex
- lib/level_web/schema/objects.ex
- lib/level_web/schema/subscriptions.ex
- priv/repo/migrations/20181003182443_create_post_versions.exs
- priv/repo/structure.sql
- test/level/posts_test.exs
- test/level_web/graphql/mutations/update_post_test.exs
- test/level_web/graphql/queries/post_test.exs
- test/level_web/graphql/subscriptions/post_updated_test.exs
> Edit posts

- assets/elm/src/Component/Post.elm
- assets/elm/src/Mutation/UpdateReply.elm
- assets/elm/src/Reply.elm
- assets/elm/src/View/Helpers.elm
- lib/level/events.ex
- lib/level/mutations.ex
- lib/level/posts.ex
- lib/level/posts/post_log.ex
- lib/level/posts/update_reply.ex
- lib/level/reply_version.ex
- lib/level/resolvers.ex
- lib/level_web/schema.ex
- lib/level_web/schema/mutations.ex
- lib/level_web/schema/objects.ex
- lib/level_web/schema/subscriptions.ex
- priv/repo/migrations/20181005154158_create_reply_versions.exs
- priv/repo/structure.sql
- test/level_web/graphql/mutations/update_reply_test.exs
- test/level_web/graphql/queries/replies_test.exs
- test/level_web/graphql/subscriptions/reply_updated_test.exs
> Edit replies

- lib/level_web/templates/page/index.html.eex
Updating the phrase "The year is 2018" to reflect the current year.
> Update year in initial copy
